export const LANG_OPTIONS: { code: string; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'ru', label: 'Русский' },
  { code: 'ro', label: 'Română' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'de', label: 'Deutsch' },
  { code: 'it', label: 'Italiano' },
  { code: 'pt', label: 'Português' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'pl', label: 'Polski' },
  { code: 'uk', label: 'Українська' },
  { code: 'ar', label: 'العربية' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'zh', label: '中文' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
];

export const STRINGS: Record<string, Record<string, string>> = {
  en: {
    add: 'ADD (FILES OR FOLDER)',
    generate: 'GENERATE METADATA',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    details: 'Details',
    selectRow: 'Select a row.',
    file: 'File',
    status: 'Status',
    visibility: 'Visibility',
    madeForKids: 'Made for kids',
    schedule: 'Schedule',
    publish: 'Publish',
    recalculate: 'Recalculate',
    applyPlan: 'Apply plan',
    editsTz: 'Edits are applied in the selected time zone',
    resetAuto: 'Reset to auto plan',
    autoPlan: 'Auto plan',
    metadata: 'Metadata',
    platform: 'Platform',
    title: 'Title',
    description: 'Description',
    hashtags: 'Hashtags',
    copy: 'Copy',
    copyAll: 'Copy all',
    copied: 'Copied',
    openExports: 'Open exports',
    openOutputs: 'Open outputs',
    reload: 'Reload',
    source: 'Source',
    pipelineLog: 'Pipeline Log',
    noRow: 'No row selected.',
    settings: 'Settings',
    uiSize: 'UI size',
    theme: 'Theme',
    day: 'Day',
    night: 'Night',
    language: 'Language',
    account: 'Account',
    manageBilling: 'Manage billing',
    subscription: 'Subscription',
    comingSoon: 'Coming soon',
    collapseAll: 'Collapse',
    expandAll: 'Expand',
    dragDropFiles: 'Drop video files here',
    dragDropFormats: 'Supported formats: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Remove',
    sortBy: 'Sort by',
    sortByName: 'Name (A-Z)',
    sortByDate: 'Creation date',
    sortByAdded: 'Added order',
    noVideoFiles: 'No video files found. Supported formats: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'video file(s) added',
    tooltipAdd: 'Add video files or folders to the list',
    tooltipGenerate: 'Generate metadata (title, description, hashtags) for selected videos using AI',
    tooltipAutoSchedule: 'Automatically assign publish times based on schedule settings',
    tooltipAutoPlan: 'Automatically assign publish times using the current schedule defaults (videos/day, times, time zone)',
    tooltipAutoUpload: 'Enable automatic upload scheduler. YouTube: full auto. Instagram/TikTok: manual assist',
    tooltipSilentMode: 'Silent mode: Only send notification, don\'t open browser automatically (prevents interruption)',
    savedMetadata: 'Saved metadata',
    savedMetadataTooltip: 'Open saved metadata templates and apply them to the selected item(s).',
    silentModeOnDesc: 'Silent mode ON: No automatic opening. Browser/Explorer/Clipboard will NOT run automatically. Use the overlay button to open the next assist.',
    silentModeOffDesc: 'Silent mode OFF: Automatic assist will open Browser + Explorer and copy metadata when jobs are due (overlay can still be used).',
    tooltipRecalculate: 'Recalculate publish times for all videos based on current sort order and schedule settings',
    tooltipApplyPlan: 'Apply plan to unscheduled items based on current sort order',
    tooltipConnectYouTube: 'Connect your YouTube account to enable automatic uploads',
    tooltipUploadYouTube: 'Upload selected video to YouTube immediately',
    tooltipCopy: 'Copy to clipboard',
    tooltipReload: 'Reload metadata from pipeline outputs',
    tooltipOpenExports: 'Open exports folder for this platform',
    tooltipOpenOutputs: 'Open main outputs folder',
    tooltipRemove: 'Remove this video from the list',
    tooltipSort: 'Sort videos by name, creation date, or added order',
    autoSchedule: 'Auto schedule',
    autoUpload: 'Auto upload',
    silent: 'Silent',
    connected: 'Connected',
    connectYouTube: 'Connect YouTube',
    check: 'Check',
    openUserData: 'Open UserData',
    timeZone: 'Time zone',
    notConnected: 'Not connected',
    connections: 'Connections',
    enabled: 'Enabled',
    yes: 'Yes',
    no: 'No',
    total: 'Total',
    systemInfo: 'System Info',
    architecture: 'Architecture',
    youtubeConnected: 'YouTube: Connected',
    youtubeNotConnected: 'YouTube: Not connected',
    publishAt: 'Publish at',
    plan: 'Plan',
    queue: 'Queue',
    running: 'running',
    advanced: 'Advanced',
    diagnostics: 'Diagnostics',
    developerMode: 'Developer mode',
    developerModeWarning: 'Warning: Developer mode features are for advanced users only. Use with caution.',
    debugMode: 'Debug mode',
    debugModeDescription: 'Enable verbose logging and debug information in console',
    autoCleanupOutputReports: 'Auto-cleanup output reports',
    autoCleanupOutputReportsHelper: 'Automatically deletes report files older than 30 days.',
    autoCleanOutputArtifacts: 'Auto-clean output artifacts',
    autoCleanOutputArtifactsHelper: 'Deletes Audio/Exports/Metadata/Transcripts files older than N days from the outputs folder.',
    deleteArtifactsOlderThanDays: 'Delete artifacts older than (days)',
    autoCleanArtifactsWarning: 'This affects only files inside the outputs folder. Originals are not deleted.',
    moveOutputsFolderTitle: 'Move outputs folder',
    moveOutputsFolderBody: 'Files will be copied to the new location. Optionally delete the files from the old location after verifying everything works.',
    moveOutputsFolderDeleteCheckbox: 'Delete files from the old location after move',
    moveOutputsFolderPrimary: 'Move',
    resetOutputsFolderTitle: 'Reset outputs folder',
    resetOutputsFolderBody: 'Outputs path will be reset to the default location. Files will be copied to the default location. Optionally delete the files from the old location after verifying everything works.',
    resetOutputsFolderPrimary: 'Reset',
    developerActions: 'Developer Actions',
    moreOptions: 'More options',
    stage: 'Stage',
    targets: 'Targets',
    actions: 'Actions',
    imported: 'Imported',
    processing: 'Processing',
    draftReady: 'Draft ready',
    needsReview: 'Needs review',
    needsAction: 'Needs action',
    ready: 'Ready',
    planned: 'Planned',
    publishing: 'Publishing',
    done: 'Done',
    failed: 'Failed',
    assistNow: 'Assist now',
    assistScheduled: 'Assist scheduled',
    assistDue: 'Assist due',
    markedPosted: 'Marked posted',
    scheduled: 'Scheduled',
    uploaded: 'Uploaded',
    posted: 'Posted',
    postedAt: 'Posted at',
    noMetadata: 'No metadata yet',
    useGenerateButtonAbove: 'Use the "Generate metadata" button above to create metadata.',
    openEditor: 'Open editor',
    applyTemplate: 'Apply template',
    templates: 'Templates',
    templateName: 'Template name',
    saveAsTemplate: 'Save as template',
    selectTemplate: 'Select template',
    noTemplates: 'No templates saved yet',
    createFromCurrent: 'Create from current metadata',
    deleteTemplate: 'Delete template',
    templateSaved: 'Template saved successfully',
    templateApplied: 'Template applied successfully',
    templateDeleted: 'Template deleted',
    copyCaption: 'Copy caption',
    copyHashtags: 'Copy hashtags',
    copyTitle: 'Copy title',
    openUploadPage: 'Open upload page',
    revealFile: 'Reveal file in folder',
    markAsPosted: 'Mark as posted',
    showTechnicalLog: 'Show technical log',
    simple: 'Simple',
    custom: 'Custom',
    youtubeOnly: 'YouTube only',
    allPlatforms: 'All platforms',
    metadataOnly: 'Metadata only',
    applyPlanToUnscheduled: 'Apply plan to unscheduled items',
    appliesOnlyToUnscheduled: 'Applies only to items without manually set times',
    inTime: 'in',
    openReview: 'Open review',
    editPlan: 'Edit plan',
    publishPlan: 'Publish plan',
    assistActions: 'Assist actions',
    presets: 'Presets',
    startDate: 'Start date',
    system: 'System',
    cancel: 'Cancel',
    selected: 'selected',
    removeFromProject: 'Remove from project',
    removeItemsConfirm: 'Remove {count} items from project?',
    undo: 'Undo',
    removed: 'removed',
    advancedModeComingSoon: 'Advanced mode coming soon',
    publishSelected: 'Publish selected',
    item: 'item',
    items: 'items',
    uploadAndSchedule: 'Upload + Schedule',
    createAssistReminders: 'Create assist reminders',
    generateMetadataOnly: 'Generate metadata only',
    planApplied: 'Plan applied successfully',
    publishStarted: 'Publish started',
    operationsCompleted: 'All operations completed successfully',
    publishSkippedNoTime: '{platform}: skipped {count} (no time set)',
    publishSkippedAlreadyPosted: '{platform}: skipped {count} (already posted)',
    publishButtonGenerate: 'Generate',
    publishButtonYouTube: 'Publish to YouTube',
    publishButtonAll: 'Publish to All',
    search: 'Search…',
    all: 'All',
    bulkActions: 'Bulk actions',
    setTargets: 'Set targets',
    selectTargetsDescription: 'Select which platforms to target for the selected items',
    apply: 'Apply',
    activity: 'Activity',
    copyFirstComment: 'Copy first comment',
    copyLastError: 'Copy last error',
    waitingUntilScheduledTime: 'Waiting until scheduled time',
    willNotifyYouAt: 'Will notify you at',
    noActivity: 'No activity',
    unknownError: 'Unknown error',
    scheduleSettings: 'Schedule settings',
    timesHelperText: 'Enter times separated by spaces (e.g., 09:00 13:00 18:00)',
    close: 'Close',
    deleteMetadataConfirm: 'Are you sure you want to delete {platform} metadata?',
    deleteMetadataConfirmTitle: 'Delete metadata?',
    save: 'Save',
    saving: 'Saving...',
    customInstructions: 'Custom Instructions for AI',
    customInstructionsPlaceholder: 'Enter custom instructions for metadata generation (e.g., "Use a more casual tone", "Focus on educational value")...',
    customInstructionsDescription: 'Provide custom instructions to guide AI metadata generation. These instructions will be added to the default prompt.',
    customInstructionsHint: 'Example: "Make titles more engaging and click-worthy", "Use emojis in descriptions", "Focus on SEO keywords"',
    customAI: 'Custom AI',
    saved: 'Saved',
    resetToDefault: 'Reset to Default',
    preset: 'Preset',
    saveAsNew: 'Save as new',
    updatePreset: 'Update preset',
    descriptionTemplate: 'Description Template',
    templatePlaceholders: 'Placeholders: {TITLE} {DESCRIPTION} {HASHTAGS} {CTA} {LINKS} {DISCLAIMER}. Missing placeholders are not injected.',
    blocks: 'Blocks',
    ctaBlock: 'CTA',
    linksBlock: 'Links',
    disclaimerBlock: 'Disclaimer',
    none: 'None',
    retryPipeline: 'Retry pipeline',
    retryUpload: 'Retry upload',
    row: 'row',
    rows: 'rows',
  },
  ru: {
    add: 'ДОБАВИТЬ (ФАЙЛЫ ИЛИ ПАПКУ)',
    generate: 'СГЕНЕРИРОВАТЬ METADATA',
    selectAll: 'Выбрать всё',
    deselectAll: 'Снять выбор',
    details: 'Детали',
    selectRow: 'Выберите строку.',
    file: 'Файл',
    status: 'Статус',
    visibility: 'Видимость',
    schedule: 'Расписание',
    publish: 'Публикация',
    recalculate: 'Пересчитать',
    editsTz: 'Изменения применяются в выбранной таймзоне',
    resetAuto: 'Вернуть авто-расписание',
    metadata: 'Метаданные',
    platform: 'Платформа',
    title: 'Заголовок',
    description: 'Описание',
    hashtags: 'Хэштеги',
    copy: 'Копировать',
    copyAll: 'Копировать всё',
    copied: 'Скопировано',
    openExports: 'Открыть exports',
    openOutputs: 'Открыть outputs',
    reload: 'Обновить',
    source: 'Источник',
    pipelineLog: 'Лог пайплайна',
    noRow: 'Строка не выбрана.',
    settings: 'Настройки',
    uiSize: 'Размер UI',
    theme: 'Тема',
    day: 'День',
    night: 'Ночь',
    language: 'Язык',
    account: 'Аккаунт',
    manageBilling: 'Биллинг',
    subscription: 'Подписка',
    comingSoon: 'Скоро будет',
    collapseAll: 'Свернуть',
    expandAll: 'Развернуть',
    dragDropFiles: 'Перетащите видео файлы сюда',
    dragDropFormats: 'Поддерживаемые форматы: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Удалить',
    sortBy: 'Сортировать по',
    sortByName: 'Имя (А-Я)',
    sortByDate: 'Дата создания',
    sortByAdded: 'Порядок добавления',
    noVideoFiles: 'Видео файлы не найдены. Поддерживаемые форматы: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'видео файл(ов) добавлено',
    tooltipAdd: 'Добавить видеофайлы или папки в список',
    tooltipGenerate: 'Сгенерировать метаданные (заголовок, описание, хештеги) для выбранных видео с помощью ИИ',
    tooltipAutoSchedule: 'Автоматически назначать время публикации на основе настроек расписания',
    tooltipAutoUpload: 'Включить автоматический планировщик загрузки. YouTube: полная автоматизация. Instagram/TikTok: ручная помощь',
    tooltipSilentMode: 'Тихий режим: только уведомление, не открывать браузер автоматически (предотвращает прерывание)',
    tooltipRecalculate: 'Пересчитать время публикации для всех видео на основе текущего порядка сортировки и настроек расписания',
    tooltipConnectYouTube: 'Подключить ваш аккаунт YouTube для включения автоматических загрузок',
    tooltipUploadYouTube: 'Загрузить выбранное видео на YouTube немедленно',
    tooltipCopy: 'Копировать в буфер обмена',
    tooltipReload: 'Перезагрузить метаданные из выходных данных конвейера',
    tooltipOpenExports: 'Открыть папку экспорта для этой платформы',
    tooltipOpenOutputs: 'Открыть основную папку выходных данных',
    tooltipRemove: 'Удалить это видео из списка',
    tooltipSort: 'Сортировать видео по имени, дате создания или порядку добавления',
    publishAt: 'Опубликовать в',
    deleteMetadataConfirm: 'Вы уверены, что хотите удалить метаданные для {platform}?',
    deleteMetadataConfirmTitle: 'Удалить метаданные?',
    save: 'Сохранить',
    saving: 'Сохранение...',
    customInstructions: 'Пользовательские инструкции для ИИ',
    customInstructionsPlaceholder: 'Введите пользовательские инструкции для генерации метаданных (например, "Используйте более неформальный тон", "Сосредоточьтесь на образовательной ценности")...',
    customInstructionsDescription: 'Предоставьте пользовательские инструкции для управления генерацией метаданных ИИ. Эти инструкции будут добавлены к стандартному запросу.',
    customInstructionsHint: 'Пример: "Делайте заголовки более привлекательными", "Используйте эмодзи в описаниях", "Сосредоточьтесь на SEO-ключевых словах"',
    customAI: 'Пользовательский ИИ',
    saved: 'Сохранено',
    resetToDefault: 'Сбросить к значениям по умолчанию',
    publishStarted: 'Публикация начата',
    publishButtonGenerate: 'Сгенерировать',
    publishButtonYouTube: 'Опубликовать на YouTube',
    publishButtonAll: 'Опубликовать везде',
    posted: 'Опубликовано',
    postedAt: 'Опубликовано в',
  },
  ro: {
    add: 'ADĂUGAȚI (FIȘIERE SAU FOLDER)',
    generate: 'GENEREAZĂ METADATE',
    selectAll: 'Selectează tot',
    deselectAll: 'Deselectează',
    details: 'Detalii',
    selectRow: 'Selectați un rând.',
    file: 'Fișier',
    status: 'Stare',
    visibility: 'Vizibilitate',
    madeForKids: 'Pentru copii',
    schedule: 'Programare',
    publish: 'Publicare',
    recalculate: 'Recalculează',
    editsTz: 'Editările se aplică în fusul orar selectat',
    resetAuto: 'Resetează la auto',
    metadata: 'Metadate',
    platform: 'Platformă',
    title: 'Titlu',
    description: 'Descriere',
    hashtags: 'Hashtag-uri',
    copy: 'Copiază',
    copyAll: 'Copiază tot',
    copied: 'Copiat',
    openExports: 'Deschide exports',
    openOutputs: 'Deschide outputs',
    reload: 'Reîncarcă',
    source: 'Sursă',
    pipelineLog: 'Jurnal pipeline',
    noRow: 'Niciun rând selectat.',
    settings: 'Setări',
    uiSize: 'Dimensiune UI',
    theme: 'Temă',
    day: 'Zi',
    night: 'Noapte',
    language: 'Limbă',
    account: 'Cont',
    manageBilling: 'Facturare',
    subscription: 'Abonament',
    comingSoon: 'În curând',
    collapseAll: 'Restrânge',
    expandAll: 'Extinde',
    dragDropFiles: 'Trage fișierele video aici',
    dragDropFormats: 'Formate acceptate: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Elimină',
    sortBy: 'Sortează după',
    sortByName: 'Nume (A-Z)',
    sortByDate: 'Data creării',
    sortByAdded: 'Ordinea adăugării',
    noVideoFiles: 'Nu s-au găsit fișiere video. Formate acceptate: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'fișier(e) video adăugat(e)',
    tooltipAdd: 'Adaugă fișiere video sau foldere în listă',
    tooltipGenerate: 'Generează metadata (titlu, descriere, hashtag-uri) pentru videourile selectate folosind AI',
    tooltipAutoSchedule: 'Atribuie automat timpuri de publicare pe baza setărilor de programare',
    tooltipAutoUpload: 'Activează planificatorul automat de încărcare. YouTube: complet automat. Instagram/TikTok: asistență manuală',
    tooltipSilentMode: 'Mod silențios: doar notificare, nu deschide browser-ul automat (previne întreruperi)',
    savedMetadata: 'Metadata salvată',
    savedMetadataTooltip: 'Deschide șabloanele de metadata salvate și le aplică elementelor selectate.',
    silentModeOnDesc: 'Mod silențios PORNIT: Nicio deschidere automată. Browser/Explorer/Clipboard NU vor rula automat. Folosește butonul overlay pentru următorul assist.',
    silentModeOffDesc: 'Mod silențios OPRIT: Assist-ul automat va deschide Browser + Explorer și va copia metadata când joburile sunt due (overlay poate fi folosit în continuare).',
    tooltipRecalculate: 'Recalculează timpurile de publicare pentru toate videourile pe baza ordinii curente de sortare și setărilor de programare',
    tooltipConnectYouTube: 'Conectează contul tău YouTube pentru a activa încărcările automate',
    tooltipUploadYouTube: 'Încarcă videoul selectat pe YouTube imediat',
    tooltipCopy: 'Copiază în clipboard',
    tooltipReload: 'Reîncarcă metadata din rezultatele pipeline-ului',
    tooltipOpenExports: 'Deschide folderul de exporturi pentru această platformă',
    tooltipOpenOutputs: 'Deschide folderul principal de rezultate',
    tooltipRemove: 'Elimină acest videou din listă',
    tooltipSort: 'Sortează videourile după nume, data creării sau ordinea adăugării',
    autoSchedule: 'Auto programare',
    autoUpload: 'Auto încărcare',
    silent: 'Silențios',
    connected: 'Conectat',
    connectYouTube: 'Conectează YouTube',
    check: 'Verifică',
    openUserData: 'Deschide UserData',
    timeZone: 'Fus orar',
    notConnected: 'Neconectat',
    youtubeConnected: 'YouTube: Conectat',
    youtubeNotConnected: 'YouTube: Neconectat',
    publishAt: 'Publicare la',
    deleteMetadataConfirm: 'Ești sigur că vrei să ștergi metadatele pentru {platform}?',
    deleteMetadataConfirmTitle: 'Șterge metadatele?',
    save: 'Salvează',
    saving: 'Se salvează...',
    customInstructions: 'Instrucțiuni personalizate pentru AI',
    customInstructionsPlaceholder: 'Introdu instrucțiuni personalizate pentru generarea metadatelor (ex: "Folosește un ton mai casual", "Concentrează-te pe valoarea educațională")...',
    customInstructionsDescription: 'Furnizează instrucțiuni personalizate pentru a ghida generarea metadatelor AI. Aceste instrucțiuni vor fi adăugate la prompt-ul implicit.',
    customInstructionsHint: 'Exemplu: "Fă titlurile mai atractive", "Folosește emoji-uri în descrieri", "Concentrează-te pe cuvinte cheie SEO"',
    customAI: 'AI Personalizat',
    saved: 'Salvat',
    resetToDefault: 'Resetează la valorile implicite',
    publishStarted: 'Publicare începută',
    operationsCompleted: 'Operațiile s-au finalizat cu succes',
    publishSkippedNoTime: '{platform}: ignorat {count} (nu e setată nicio oră)',
    publishSkippedAlreadyPosted: '{platform}: ignorat {count} (deja postat)',
    publishButtonGenerate: 'Generează',
    publishButtonYouTube: 'Publică pe YouTube',
    publishButtonAll: 'Publică peste tot',
    posted: 'Publicat',
    postedAt: 'Publicat la',
  },
  es: {
    add: 'AGREGAR (ARCHIVOS O CARPETA)',
    generate: 'GENERAR METADATOS',
    selectAll: 'Seleccionar todo',
    deselectAll: 'Deseleccionar todo',
    details: 'Detalles',
    selectRow: 'Seleccione una fila.',
    file: 'Archivo',
    status: 'Estado',
    visibility: 'Visibilidad',
    schedule: 'Programar',
    publish: 'Publicar',
    recalculate: 'Recalcular',
    editsTz: 'Las ediciones se aplican en la zona horaria seleccionada',
    resetAuto: 'Restablecer a programación automática',
    metadata: 'Metadatos',
    platform: 'Plataforma',
    title: 'Título',
    description: 'Descripción',
    hashtags: 'Hashtags',
    copy: 'Copiar',
    copyAll: 'Copiar todo',
    copied: 'Copiado',
    openExports: 'Abrir exports',
    openOutputs: 'Abrir outputs',
    reload: 'Recargar',
    source: 'Fuente',
    pipelineLog: 'Registro del pipeline',
    noRow: 'No se seleccionó ninguna fila.',
    settings: 'Configuración',
    uiSize: 'Tamaño de UI',
    theme: 'Tema',
    day: 'Día',
    night: 'Noche',
    language: 'Idioma',
    account: 'Cuenta',
    manageBilling: 'Gestionar facturación',
    subscription: 'Suscripción',
    comingSoon: 'Próximamente',
    collapseAll: 'Contraer',
    expandAll: 'Expandir',
    dragDropFiles: 'Arrastra archivos de video aquí',
    dragDropFormats: 'Formatos admitidos: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Eliminar',
    sortBy: 'Ordenar por',
    sortByName: 'Nombre (A-Z)',
    sortByDate: 'Fecha de creación',
    sortByAdded: 'Orden de adición',
    noVideoFiles: 'No se encontraron archivos de video. Formatos admitidos: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'archivo(s) de video agregado(s)',
    tooltipAdd: 'Agregar archivos de video o carpetas a la lista',
    tooltipGenerate: 'Generar metadatos (título, descripción, hashtags) para videos seleccionados usando IA',
    tooltipAutoSchedule: 'Asignar automáticamente horarios de publicación según la configuración del programa',
    tooltipAutoUpload: 'Habilitar programador de carga automática. YouTube: completamente automático. Instagram/TikTok: asistencia manual',
    tooltipSilentMode: 'Modo silencioso: solo notificación, no abrir el navegador automáticamente (previene interrupciones)',
    tooltipRecalculate: 'Recalcular horarios de publicación para todos los videos según el orden de clasificación actual y la configuración del programa',
    tooltipConnectYouTube: 'Conectar tu cuenta de YouTube para habilitar cargas automáticas',
    tooltipUploadYouTube: 'Subir el video seleccionado a YouTube inmediatamente',
    tooltipCopy: 'Copiar al portapapeles',
    tooltipReload: 'Recargar metadatos desde las salidas del pipeline',
    tooltipOpenExports: 'Abrir carpeta de exports para esta plataforma',
    tooltipOpenOutputs: 'Abrir carpeta principal de outputs',
    tooltipRemove: 'Eliminar este video de la lista',
    tooltipSort: 'Ordenar videos por nombre, fecha de creación u orden de adición',
    autoSchedule: 'Programación automática',
    autoUpload: 'Carga automática',
    silent: 'Silencioso',
    connected: 'Conectado',
    connectYouTube: 'Conectar YouTube',
    check: 'Verificar',
    openUserData: 'Abrir UserData',
    timeZone: 'Zona horaria',
    notConnected: 'No conectado',
    youtubeConnected: 'YouTube: Conectado',
    youtubeNotConnected: 'YouTube: No conectado',
    publishAt: 'Publicar en',
    deleteMetadataConfirm: '¿Estás seguro de que quieres eliminar los metadatos de {platform}?',
    deleteMetadataConfirmTitle: '¿Eliminar metadatos?',
    publishStarted: 'Publicación iniciada',
    publishButtonGenerate: 'Generar',
    publishButtonYouTube: 'Publicar en YouTube',
    publishButtonAll: 'Publicar en todas',
    posted: 'Publicado',
    postedAt: 'Publicado el',
  },
  fr: {
    add: 'AJOUTER (FICHIERS OU DOSSIER)',
    generate: 'GÉNÉRER MÉTADONNÉES',
    selectAll: 'Tout sélectionner',
    deselectAll: 'Tout désélectionner',
    details: 'Détails',
    selectRow: 'Sélectionnez une ligne.',
    file: 'Fichier',
    status: 'Statut',
    visibility: 'Visibilité',
    schedule: 'Planifier',
    publish: 'Publier',
    recalculate: 'Recalculer',
    editsTz: 'Les modifications sont appliquées dans le fuseau horaire sélectionné',
    resetAuto: 'Réinitialiser à la planification automatique',
    metadata: 'Métadonnées',
    platform: 'Plateforme',
    title: 'Titre',
    description: 'Description',
    hashtags: 'Hashtags',
    copy: 'Copier',
    copyAll: 'Tout copier',
    copied: 'Copié',
    openExports: 'Ouvrir exports',
    openOutputs: 'Ouvrir outputs',
    reload: 'Recharger',
    source: 'Source',
    pipelineLog: 'Journal du pipeline',
    noRow: 'Aucune ligne sélectionnée.',
    settings: 'Paramètres',
    uiSize: 'Taille de l\'interface',
    theme: 'Thème',
    day: 'Jour',
    night: 'Nuit',
    language: 'Langue',
    account: 'Compte',
    manageBilling: 'Gérer la facturation',
    subscription: 'Abonnement',
    comingSoon: 'Bientôt disponible',
    collapseAll: 'Réduire',
    expandAll: 'Développer',
    dragDropFiles: 'Déposez les fichiers vidéo ici',
    dragDropFormats: 'Formats pris en charge: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Supprimer',
    sortBy: 'Trier par',
    sortByName: 'Nom (A-Z)',
    sortByDate: 'Date de création',
    sortByAdded: 'Ordre d\'ajout',
    noVideoFiles: 'Aucun fichier vidéo trouvé. Formats pris en charge: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'fichier(s) vidéo ajouté(s)',
    tooltipAdd: 'Ajouter des fichiers vidéo ou des dossiers à la liste',
    tooltipGenerate: 'Générer des métadonnées (titre, description, hashtags) pour les vidéos sélectionnées en utilisant l\'IA',
    tooltipAutoSchedule: 'Attribuer automatiquement les heures de publication en fonction des paramètres de planification',
    tooltipAutoUpload: 'Activer le planificateur de téléchargement automatique. YouTube: entièrement automatique. Instagram/TikTok: assistance manuelle',
    tooltipSilentMode: 'Mode silencieux: notification uniquement, ne pas ouvrir le navigateur automatiquement (évite les interruptions)',
    tooltipRecalculate: 'Recalculer les heures de publication pour toutes les vidéos en fonction de l\'ordre de tri actuel et des paramètres de planification',
    tooltipConnectYouTube: 'Connecter votre compte YouTube pour activer les téléchargements automatiques',
    tooltipUploadYouTube: 'Télécharger la vidéo sélectionnée sur YouTube immédiatement',
    tooltipCopy: 'Copier dans le presse-papiers',
    tooltipReload: 'Recharger les métadonnées depuis les sorties du pipeline',
    tooltipOpenExports: 'Ouvrir le dossier exports pour cette plateforme',
    tooltipOpenOutputs: 'Ouvrir le dossier principal outputs',
    tooltipRemove: 'Supprimer cette vidéo de la liste',
    tooltipSort: 'Trier les vidéos par nom, date de création ou ordre d\'ajout',
    autoSchedule: 'Planification automatique',
    autoUpload: 'Téléchargement automatique',
    silent: 'Silencieux',
    connected: 'Connecté',
    connectYouTube: 'Connecter YouTube',
    check: 'Vérifier',
    openUserData: 'Ouvrir UserData',
    timeZone: 'Fuseau horaire',
    notConnected: 'Non connecté',
    youtubeConnected: 'YouTube: Connecté',
    youtubeNotConnected: 'YouTube: Non connecté',
    publishAt: 'Publier à',
    deleteMetadataConfirm: 'Êtes-vous sûr de vouloir supprimer les métadonnées de {platform}?',
    deleteMetadataConfirmTitle: 'Supprimer les métadonnées?',
    publishStarted: 'Publication démarrée',
    publishButtonGenerate: 'Générer',
    publishButtonYouTube: 'Publier sur YouTube',
    publishButtonAll: 'Publier partout',
    posted: 'Publié',
    postedAt: 'Publié le',
  },
  de: {
    add: 'HINZUFÜGEN (DATEIEN ODER ORDNER)',
    generate: 'METADATEN GENERIEREN',
    selectAll: 'Alle auswählen',
    deselectAll: 'Alle abwählen',
    details: 'Details',
    selectRow: 'Wählen Sie eine Zeile aus.',
    file: 'Datei',
    status: 'Status',
    visibility: 'Sichtbarkeit',
    schedule: 'Planen',
    publish: 'Veröffentlichen',
    recalculate: 'Neu berechnen',
    editsTz: 'Änderungen werden in der ausgewählten Zeitzone angewendet',
    resetAuto: 'Auf automatische Planung zurücksetzen',
    metadata: 'Metadaten',
    platform: 'Plattform',
    title: 'Titel',
    description: 'Beschreibung',
    hashtags: 'Hashtags',
    copy: 'Kopieren',
    copyAll: 'Alles kopieren',
    copied: 'Kopiert',
    openExports: 'Exports öffnen',
    openOutputs: 'Outputs öffnen',
    reload: 'Neu laden',
    source: 'Quelle',
    pipelineLog: 'Pipeline-Protokoll',
    noRow: 'Keine Zeile ausgewählt.',
    settings: 'Einstellungen',
    uiSize: 'UI-Größe',
    theme: 'Thema',
    day: 'Tag',
    night: 'Nacht',
    language: 'Sprache',
    account: 'Konto',
    manageBilling: 'Abrechnung verwalten',
    subscription: 'Abonnement',
    comingSoon: 'Demnächst',
    collapseAll: 'Einklappen',
    expandAll: 'Ausklappen',
    dragDropFiles: 'Video-Dateien hier ablegen',
    dragDropFormats: 'Unterstützte Formate: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Entfernen',
    sortBy: 'Sortieren nach',
    sortByName: 'Name (A-Z)',
    sortByDate: 'Erstellungsdatum',
    sortByAdded: 'Hinzufügungsreihenfolge',
    noVideoFiles: 'Keine Video-Dateien gefunden. Unterstützte Formate: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'Video-Datei(en) hinzugefügt',
    tooltipAdd: 'Video-Dateien oder Ordner zur Liste hinzufügen',
    tooltipGenerate: 'Metadaten (Titel, Beschreibung, Hashtags) für ausgewählte Videos mit KI generieren',
    tooltipAutoSchedule: 'Veröffentlichungszeiten automatisch basierend auf Planungseinstellungen zuweisen',
    tooltipAutoUpload: 'Automatischen Upload-Planer aktivieren. YouTube: vollautomatisch. Instagram/TikTok: manuelle Unterstützung',
    tooltipSilentMode: 'Stiller Modus: Nur Benachrichtigung, Browser nicht automatisch öffnen (verhindert Unterbrechungen)',
    tooltipRecalculate: 'Veröffentlichungszeiten für alle Videos basierend auf aktueller Sortierreihenfolge und Planungseinstellungen neu berechnen',
    tooltipConnectYouTube: 'Ihr YouTube-Konto verbinden, um automatische Uploads zu aktivieren',
    tooltipUploadYouTube: 'Ausgewähltes Video sofort auf YouTube hochladen',
    tooltipCopy: 'In Zwischenablage kopieren',
    tooltipReload: 'Metadaten aus Pipeline-Ausgaben neu laden',
    tooltipOpenExports: 'Exports-Ordner für diese Plattform öffnen',
    tooltipOpenOutputs: 'Haupt-Outputs-Ordner öffnen',
    tooltipRemove: 'Dieses Video aus der Liste entfernen',
    tooltipSort: 'Videos nach Name, Erstellungsdatum oder Hinzufügungsreihenfolge sortieren',
    autoSchedule: 'Automatische Planung',
    autoUpload: 'Automatischer Upload',
    silent: 'Stumm',
    connected: 'Verbunden',
    connectYouTube: 'YouTube verbinden',
    check: 'Prüfen',
    openUserData: 'UserData öffnen',
    timeZone: 'Zeitzone',
    notConnected: 'Nicht verbunden',
    youtubeConnected: 'YouTube: Verbunden',
    youtubeNotConnected: 'YouTube: Nicht verbunden',
    publishAt: 'Veröffentlichen um',
    deleteMetadataConfirm: 'Sind Sie sicher, dass Sie die Metadaten für {platform} löschen möchten?',
    deleteMetadataConfirmTitle: 'Metadaten löschen?',
    publishStarted: 'Veröffentlichung gestartet',
    publishButtonGenerate: 'Generieren',
    publishButtonYouTube: 'Auf YouTube veröffentlichen',
    publishButtonAll: 'Überall veröffentlichen',
    posted: 'Veröffentlicht',
    postedAt: 'Veröffentlicht am',
  },
  it: {
    add: 'AGGIUNGI (FILE O CARTELLA)',
    generate: 'GENERA METADATI',
    selectAll: 'Seleziona tutto',
    deselectAll: 'Deseleziona tutto',
    details: 'Dettagli',
    selectRow: 'Seleziona una riga.',
    file: 'File',
    status: 'Stato',
    visibility: 'Visibilità',
    schedule: 'Programma',
    publish: 'Pubblica',
    recalculate: 'Ricalcola',
    editsTz: 'Le modifiche vengono applicate nel fuso orario selezionato',
    resetAuto: 'Ripristina alla programmazione automatica',
    metadata: 'Metadati',
    platform: 'Piattaforma',
    title: 'Titolo',
    description: 'Descrizione',
    hashtags: 'Hashtag',
    copy: 'Copia',
    copyAll: 'Copia tutto',
    copied: 'Copiato',
    openExports: 'Apri exports',
    openOutputs: 'Apri outputs',
    reload: 'Ricarica',
    source: 'Sorgente',
    pipelineLog: 'Registro pipeline',
    noRow: 'Nessuna riga selezionata.',
    settings: 'Impostazioni',
    uiSize: 'Dimensione UI',
    theme: 'Tema',
    day: 'Giorno',
    night: 'Notte',
    language: 'Lingua',
    account: 'Account',
    manageBilling: 'Gestisci fatturazione',
    subscription: 'Abbonamento',
    comingSoon: 'Prossimamente',
    collapseAll: 'Comprimi',
    expandAll: 'Espandi',
    dragDropFiles: 'Trascina i file video qui',
    dragDropFormats: 'Formati supportati: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Rimuovi',
    sortBy: 'Ordina per',
    sortByName: 'Nome (A-Z)',
    sortByDate: 'Data di creazione',
    sortByAdded: 'Ordine di aggiunta',
    noVideoFiles: 'Nessun file video trovato. Formati supportati: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'file video aggiunto/i',
    tooltipAdd: 'Aggiungi file video o cartelle all\'elenco',
    tooltipGenerate: 'Genera metadati (titolo, descrizione, hashtag) per i video selezionati utilizzando l\'IA',
    tooltipAutoSchedule: 'Assegna automaticamente gli orari di pubblicazione in base alle impostazioni di programmazione',
    tooltipAutoUpload: 'Abilita il pianificatore di caricamento automatico. YouTube: completamente automatico. Instagram/TikTok: assistenza manuale',
    tooltipSilentMode: 'Modalità silenziosa: solo notifica, non aprire il browser automaticamente (previene interruzioni)',
    tooltipRecalculate: 'Ricalcola gli orari di pubblicazione per tutti i video in base all\'ordine di ordinamento corrente e alle impostazioni di programmazione',
    tooltipConnectYouTube: 'Connetti il tuo account YouTube per abilitare i caricamenti automatici',
    tooltipUploadYouTube: 'Carica il video selezionato su YouTube immediatamente',
    tooltipCopy: 'Copia negli appunti',
    tooltipReload: 'Ricarica i metadati dalle uscite della pipeline',
    tooltipOpenExports: 'Apri la cartella exports per questa piattaforma',
    tooltipOpenOutputs: 'Apri la cartella principale outputs',
    tooltipRemove: 'Rimuovi questo video dall\'elenco',
    tooltipSort: 'Ordina i video per nome, data di creazione o ordine di aggiunta',
    autoSchedule: 'Pianificazione automatica',
    autoUpload: 'Caricamento automatico',
    silent: 'Silenzioso',
    connected: 'Connesso',
    connectYouTube: 'Connetti YouTube',
    check: 'Verifica',
    openUserData: 'Apri UserData',
    timeZone: 'Fuso orario',
    notConnected: 'Non connesso',
    youtubeConnected: 'YouTube: Connesso',
    youtubeNotConnected: 'YouTube: Non connesso',
    publishAt: 'Pubblica alle',
    deleteMetadataConfirm: 'Sei sicuro di voler eliminare i metadati per {platform}?',
    deleteMetadataConfirmTitle: 'Eliminare metadati?',
    publishStarted: 'Pubblicazione avviata',
    publishButtonGenerate: 'Genera',
    publishButtonYouTube: 'Pubblica su YouTube',
    publishButtonAll: 'Pubblica ovunque',
    posted: 'Pubblicato',
    postedAt: 'Pubblicato alle',
  },
  pt: {
    add: 'ADICIONAR (ARQUIVOS OU PASTA)',
    generate: 'GERAR METADADOS',
    selectAll: 'Selecionar tudo',
    deselectAll: 'Desselecionar tudo',
    details: 'Detalhes',
    selectRow: 'Selecione uma linha.',
    file: 'Arquivo',
    status: 'Status',
    visibility: 'Visibilidade',
    schedule: 'Agendar',
    publish: 'Publicar',
    recalculate: 'Recalcular',
    editsTz: 'As edições são aplicadas no fuso horário selecionado',
    resetAuto: 'Redefinir para agendamento automático',
    metadata: 'Metadados',
    platform: 'Plataforma',
    title: 'Título',
    description: 'Descrição',
    hashtags: 'Hashtags',
    copy: 'Copiar',
    copyAll: 'Copiar tudo',
    copied: 'Copiado',
    openExports: 'Abrir exports',
    openOutputs: 'Abrir outputs',
    reload: 'Recarregar',
    source: 'Fonte',
    pipelineLog: 'Registro do pipeline',
    noRow: 'Nenhuma linha selecionada.',
    settings: 'Configurações',
    uiSize: 'Tamanho da UI',
    theme: 'Tema',
    day: 'Dia',
    night: 'Noite',
    language: 'Idioma',
    account: 'Conta',
    manageBilling: 'Gerenciar cobrança',
    subscription: 'Assinatura',
    comingSoon: 'Em breve',
    collapseAll: 'Recolher',
    expandAll: 'Expandir',
    dragDropFiles: 'Arraste arquivos de vídeo aqui',
    dragDropFormats: 'Formatos suportados: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Remover',
    sortBy: 'Ordenar por',
    sortByName: 'Nome (A-Z)',
    sortByDate: 'Data de criação',
    sortByAdded: 'Ordem de adição',
    noVideoFiles: 'Nenhum arquivo de vídeo encontrado. Formatos suportados: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'arquivo(s) de vídeo adicionado(s)',
    tooltipAdd: 'Adicionar arquivos de vídeo ou pastas à lista',
    tooltipGenerate: 'Gerar metadados (título, descrição, hashtags) para vídeos selecionados usando IA',
    tooltipAutoSchedule: 'Atribuir automaticamente horários de publicação com base nas configurações de agendamento',
    tooltipAutoUpload: 'Habilitar agendador de upload automático. YouTube: totalmente automático. Instagram/TikTok: assistência manual',
    tooltipSilentMode: 'Modo silencioso: apenas notificação, não abrir o navegador automaticamente (previne interrupções)',
    tooltipRecalculate: 'Recalcular horários de publicação para todos os vídeos com base na ordem de classificação atual e configurações de agendamento',
    tooltipConnectYouTube: 'Conectar sua conta do YouTube para habilitar uploads automáticos',
    tooltipUploadYouTube: 'Fazer upload do vídeo selecionado para o YouTube imediatamente',
    tooltipCopy: 'Copiar para a área de transferência',
    tooltipReload: 'Recarregar metadados das saídas do pipeline',
    tooltipOpenExports: 'Abrir pasta de exports para esta plataforma',
    tooltipOpenOutputs: 'Abrir pasta principal de outputs',
    tooltipRemove: 'Remover este vídeo da lista',
    tooltipSort: 'Ordenar vídeos por nome, data de criação ou ordem de adição',
    autoSchedule: 'Agendamento automático',
    autoUpload: 'Upload automático',
    silent: 'Silencioso',
    connected: 'Conectado',
    connectYouTube: 'Conectar YouTube',
    check: 'Verificar',
    openUserData: 'Abrir UserData',
    timeZone: 'Fuso horário',
    notConnected: 'Não conectado',
    youtubeConnected: 'YouTube: Conectado',
    youtubeNotConnected: 'YouTube: Não conectado',
    publishAt: 'Publicar em',
    deleteMetadataConfirm: 'Tem certeza de que deseja excluir os metadados de {platform}?',
    deleteMetadataConfirmTitle: 'Excluir metadados?',
    publishStarted: 'Publicação iniciada',
    publishButtonGenerate: 'Gerar',
    publishButtonYouTube: 'Publicar no YouTube',
    publishButtonAll: 'Publicar em todas',
    posted: 'Publicado',
    postedAt: 'Publicado em',
  },
  tr: {
    add: 'EKLE (DOSYALAR VEYA KLASÖR)',
    generate: 'METADATA OLUŞTUR',
    selectAll: 'Tümünü seç',
    deselectAll: 'Tümünü kaldır',
    details: 'Detaylar',
    selectRow: 'Bir satır seçin.',
    file: 'Dosya',
    status: 'Durum',
    visibility: 'Görünürlük',
    schedule: 'Zamanla',
    publish: 'Yayınla',
    recalculate: 'Yeniden hesapla',
    editsTz: 'Düzenlemeler seçilen saat diliminde uygulanır',
    resetAuto: 'Otomatik zamanlamaya sıfırla',
    metadata: 'Metadata',
    platform: 'Platform',
    title: 'Başlık',
    description: 'Açıklama',
    hashtags: 'Hashtag\'ler',
    copy: 'Kopyala',
    copyAll: 'Tümünü kopyala',
    copied: 'Kopyalandı',
    openExports: 'Exports\'u aç',
    openOutputs: 'Outputs\'u aç',
    reload: 'Yeniden yükle',
    source: 'Kaynak',
    pipelineLog: 'Pipeline günlüğü',
    noRow: 'Hiçbir satır seçilmedi.',
    settings: 'Ayarlar',
    uiSize: 'UI boyutu',
    theme: 'Tema',
    day: 'Gün',
    night: 'Gece',
    language: 'Dil',
    account: 'Hesap',
    manageBilling: 'Faturalamayı yönet',
    subscription: 'Abonelik',
    comingSoon: 'Yakında',
    collapseAll: 'Daralt',
    expandAll: 'Genişlet',
    dragDropFiles: 'Video dosyalarını buraya sürükleyin',
    dragDropFormats: 'Desteklenen formatlar: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Kaldır',
    sortBy: 'Sırala',
    sortByName: 'İsim (A-Z)',
    sortByDate: 'Oluşturma tarihi',
    sortByAdded: 'Ekleme sırası',
    noVideoFiles: 'Video dosyası bulunamadı. Desteklenen formatlar: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'video dosyası eklendi',
    tooltipAdd: 'Listeye video dosyaları veya klasörler ekle',
    tooltipGenerate: 'Seçilen videolar için AI kullanarak metadata (başlık, açıklama, hashtag\'ler) oluştur',
    tooltipAutoSchedule: 'Zamanlama ayarlarına göre otomatik olarak yayın saatleri ata',
    tooltipAutoUpload: 'Otomatik yükleme zamanlayıcısını etkinleştir. YouTube: tam otomatik. Instagram/TikTok: manuel yardım',
    tooltipSilentMode: 'Sessiz mod: sadece bildirim gönder, tarayıcıyı otomatik açma (kesintileri önler)',
    tooltipRecalculate: 'Mevcut sıralama düzenine ve zamanlama ayarlarına göre tüm videolar için yayın saatlerini yeniden hesapla',
    tooltipConnectYouTube: 'Otomatik yüklemeleri etkinleştirmek için YouTube hesabınızı bağlayın',
    tooltipUploadYouTube: 'Seçilen videoyu hemen YouTube\'a yükle',
    tooltipCopy: 'Panoya kopyala',
    tooltipReload: 'Pipeline çıktılarından metadata\'yı yeniden yükle',
    tooltipOpenExports: 'Bu platform için exports klasörünü aç',
    tooltipOpenOutputs: 'Ana outputs klasörünü aç',
    tooltipRemove: 'Bu videoyu listeden kaldır',
    tooltipSort: 'Videoları isme, oluşturma tarihine veya ekleme sırasına göre sırala',
    autoSchedule: 'Otomatik zamanlama',
    autoUpload: 'Otomatik yükleme',
    silent: 'Sessiz',
    connected: 'Bağlı',
    connectYouTube: 'YouTube bağla',
    check: 'Kontrol et',
    openUserData: 'UserData aç',
    timeZone: 'Saat dilimi',
    notConnected: 'Bağlı değil',
    youtubeConnected: 'YouTube: Bağlı',
    youtubeNotConnected: 'YouTube: Bağlı değil',
    publishAt: 'Yayınla',
    deleteMetadataConfirm: '{platform} için metadata\'yı silmek istediğinizden emin misiniz?',
    deleteMetadataConfirmTitle: 'Metadata silinsin mi?',
    publishStarted: 'Yayın başlatıldı',
    publishButtonGenerate: 'Oluştur',
    publishButtonYouTube: 'YouTube\'a Yayınla',
    publishButtonAll: 'Her Yere Yayınla',
    posted: 'Yayınlandı',
    postedAt: 'Yayınlandı',
  },
  pl: {
    add: 'DODAJ (PLIKI LUB FOLDER)',
    generate: 'GENERUJ METADANE',
    selectAll: 'Zaznacz wszystko',
    deselectAll: 'Odznacz wszystko',
    details: 'Szczegóły',
    selectRow: 'Wybierz wiersz.',
    file: 'Plik',
    status: 'Status',
    visibility: 'Widoczność',
    schedule: 'Zaplanuj',
    publish: 'Opublikuj',
    recalculate: 'Przelicz',
    editsTz: 'Edycje są stosowane w wybranej strefie czasowej',
    resetAuto: 'Przywróć automatyczne planowanie',
    metadata: 'Metadane',
    platform: 'Platforma',
    title: 'Tytuł',
    description: 'Opis',
    hashtags: 'Hasztagi',
    copy: 'Kopiuj',
    copyAll: 'Kopiuj wszystko',
    copied: 'Skopiowano',
    openExports: 'Otwórz exports',
    openOutputs: 'Otwórz outputs',
    reload: 'Przeładuj',
    source: 'Źródło',
    pipelineLog: 'Dziennik pipeline',
    noRow: 'Nie wybrano wiersza.',
    settings: 'Ustawienia',
    uiSize: 'Rozmiar UI',
    theme: 'Motyw',
    day: 'Dzień',
    night: 'Noc',
    language: 'Język',
    account: 'Konto',
    manageBilling: 'Zarządzaj rozliczeniami',
    subscription: 'Subskrypcja',
    comingSoon: 'Wkrótce',
    collapseAll: 'Zwiń',
    expandAll: 'Rozwiń',
    dragDropFiles: 'Przeciągnij pliki wideo tutaj',
    dragDropFormats: 'Obsługiwane formaty: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Usuń',
    sortBy: 'Sortuj według',
    sortByName: 'Nazwa (A-Z)',
    sortByDate: 'Data utworzenia',
    sortByAdded: 'Kolejność dodania',
    noVideoFiles: 'Nie znaleziono plików wideo. Obsługiwane formaty: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'plik(i) wideo dodane',
    tooltipAdd: 'Dodaj pliki wideo lub foldery do listy',
    tooltipGenerate: 'Generuj metadane (tytuł, opis, hasztagi) dla wybranych filmów za pomocą AI',
    tooltipAutoSchedule: 'Automatycznie przypisuj czasy publikacji na podstawie ustawień harmonogramu',
    tooltipAutoUpload: 'Włącz automatyczny harmonogram przesyłania. YouTube: w pełni automatyczny. Instagram/TikTok: pomoc ręczna',
    tooltipSilentMode: 'Tryb cichy: tylko powiadomienie, nie otwieraj przeglądarki automatycznie (zapobiega przerwom)',
    tooltipRecalculate: 'Przelicz czasy publikacji dla wszystkich filmów na podstawie bieżącego porządku sortowania i ustawień harmonogramu',
    tooltipConnectYouTube: 'Połącz swoje konto YouTube, aby włączyć automatyczne przesyłanie',
    tooltipUploadYouTube: 'Prześlij wybrany film na YouTube natychmiast',
    tooltipCopy: 'Kopiuj do schowka',
    tooltipReload: 'Przeładuj metadane z wyników pipeline',
    tooltipOpenExports: 'Otwórz folder exports dla tej platformy',
    tooltipOpenOutputs: 'Otwórz główny folder outputs',
    tooltipRemove: 'Usuń ten film z listy',
    tooltipSort: 'Sortuj filmy według nazwy, daty utworzenia lub kolejności dodania',
    autoSchedule: 'Automatyczne planowanie',
    autoUpload: 'Automatyczne przesyłanie',
    silent: 'Cichy',
    connected: 'Połączono',
    connectYouTube: 'Połącz YouTube',
    check: 'Sprawdź',
    openUserData: 'Otwórz UserData',
    timeZone: 'Strefa czasowa',
    notConnected: 'Nie połączono',
    youtubeConnected: 'YouTube: Połączono',
    youtubeNotConnected: 'YouTube: Nie połączono',
    publishAt: 'Opublikuj o',
    deleteMetadataConfirm: 'Czy na pewno chcesz usunąć metadane dla {platform}?',
    deleteMetadataConfirmTitle: 'Usunąć metadane?',
    publishStarted: 'Publikacja rozpoczęta',
    publishButtonGenerate: 'Generuj',
    publishButtonYouTube: 'Opublikuj na YouTube',
    publishButtonAll: 'Opublikuj wszędzie',
    posted: 'Opublikowano',
    postedAt: 'Opublikowano o',
  },
  uk: {
    add: 'ДОДАТИ (ФАЙЛИ АБО ПАПКУ)',
    generate: 'ЗГЕНЕРУВАТИ METADATA',
    selectAll: 'Вибрати все',
    deselectAll: 'Зняти вибір',
    details: 'Деталі',
    selectRow: 'Виберіть рядок.',
    file: 'Файл',
    status: 'Статус',
    visibility: 'Видимість',
    schedule: 'Розклад',
    publish: 'Опублікувати',
    recalculate: 'Перерахувати',
    editsTz: 'Зміни застосовуються в вибраній часовій зоні',
    resetAuto: 'Повернути авто-розклад',
    metadata: 'Метадані',
    platform: 'Платформа',
    title: 'Заголовок',
    description: 'Опис',
    hashtags: 'Хештеги',
    copy: 'Копіювати',
    copyAll: 'Копіювати все',
    copied: 'Скопійовано',
    openExports: 'Відкрити exports',
    openOutputs: 'Відкрити outputs',
    reload: 'Оновити',
    source: 'Джерело',
    pipelineLog: 'Журнал пайплайна',
    noRow: 'Рядок не вибрано.',
    settings: 'Налаштування',
    uiSize: 'Розмір UI',
    theme: 'Тема',
    day: 'День',
    night: 'Ніч',
    language: 'Мова',
    account: 'Акаунт',
    manageBilling: 'Білінг',
    subscription: 'Підписка',
    comingSoon: 'Незабаром',
    collapseAll: 'Згорнути',
    expandAll: 'Розгорнути',
    dragDropFiles: 'Перетягніть відео файли сюди',
    dragDropFormats: 'Підтримувані формати: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'Видалити',
    sortBy: 'Сортувати за',
    sortByName: 'Ім\'я (А-Я)',
    sortByDate: 'Дата створення',
    sortByAdded: 'Порядок додавання',
    noVideoFiles: 'Відео файли не знайдено. Підтримувані формати: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'відео файл(ів) додано',
    tooltipAdd: 'Додати відеофайли або папки до списку',
    tooltipGenerate: 'Згенерувати метадані (заголовок, опис, хештеги) для вибраних відео за допомогою ШІ',
    tooltipAutoSchedule: 'Автоматично призначати час публікації на основі налаштувань розкладу',
    tooltipAutoUpload: 'Увімкнути автоматичний планувальник завантаження. YouTube: повна автоматизація. Instagram/TikTok: ручна допомога',
    tooltipSilentMode: 'Тихий режим: тільки сповіщення, не відкривати браузер автоматично (запобігає перериванням)',
    tooltipRecalculate: 'Перерахувати час публікації для всіх відео на основі поточного порядку сортування та налаштувань розкладу',
    tooltipConnectYouTube: 'Підключити ваш акаунт YouTube для ввімкнення автоматичних завантажень',
    tooltipUploadYouTube: 'Завантажити вибране відео на YouTube негайно',
    tooltipCopy: 'Копіювати в буфер обміну',
    tooltipReload: 'Перезавантажити метадані з вихідних даних конвеєра',
    tooltipOpenExports: 'Відкрити папку експорту для цієї платформи',
    tooltipOpenOutputs: 'Відкрити основну папку вихідних даних',
    tooltipRemove: 'Видалити це відео зі списку',
    tooltipSort: 'Сортувати відео за ім\'ям, датою створення або порядком додавання',
    autoSchedule: 'Авто розклад',
    autoUpload: 'Авто завантаження',
    silent: 'Тихий',
    connected: 'Підключено',
    connectYouTube: 'Підключити YouTube',
    check: 'Перевірити',
    openUserData: 'Відкрити UserData',
    timeZone: 'Часовий пояс',
    notConnected: 'Не підключено',
    youtubeConnected: 'YouTube: Підключено',
    youtubeNotConnected: 'YouTube: Не підключено',
    publishAt: 'Опублікувати о',
    deleteMetadataConfirm: 'Ви впевнені, що хочете видалити метадані для {platform}?',
    deleteMetadataConfirmTitle: 'Видалити метадані?',
    publishStarted: 'Публікацію розпочато',
    publishButtonGenerate: 'Згенерувати',
    publishButtonYouTube: 'Опублікувати на YouTube',
    publishButtonAll: 'Опублікувати скрізь',
    posted: 'Опубліковано',
    postedAt: 'Опубліковано о',
  },
  ar: {
    add: 'إضافة (ملفات أو مجلد)',
    generate: 'إنشاء البيانات الوصفية',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    details: 'التفاصيل',
    selectRow: 'حدد صفًا.',
    file: 'ملف',
    status: 'الحالة',
    visibility: 'الرؤية',
    schedule: 'جدولة',
    publish: 'نشر',
    recalculate: 'إعادة الحساب',
    editsTz: 'يتم تطبيق التعديلات في المنطقة الزمنية المحددة',
    resetAuto: 'إعادة تعيين إلى الجدولة التلقائية',
    metadata: 'البيانات الوصفية',
    platform: 'المنصة',
    title: 'العنوان',
    description: 'الوصف',
    hashtags: 'الهاشتاغات',
    copy: 'نسخ',
    copyAll: 'نسخ الكل',
    copied: 'تم النسخ',
    openExports: 'فتح الصادرات',
    openOutputs: 'فتح المخرجات',
    reload: 'إعادة التحميل',
    source: 'المصدر',
    pipelineLog: 'سجل خط الأنابيب',
    noRow: 'لم يتم تحديد صف.',
    settings: 'الإعدادات',
    uiSize: 'حجم واجهة المستخدم',
    theme: 'المظهر',
    day: 'نهار',
    night: 'ليل',
    language: 'اللغة',
    account: 'الحساب',
    manageBilling: 'إدارة الفوترة',
    subscription: 'الاشتراك',
    comingSoon: 'قريبًا',
    collapseAll: 'طي',
    expandAll: 'توسيع',
    dragDropFiles: 'اسحب ملفات الفيديو هنا',
    dragDropFormats: 'الصيغ المدعومة: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'إزالة',
    sortBy: 'ترتيب حسب',
    sortByName: 'الاسم (أ-ي)',
    sortByDate: 'تاريخ الإنشاء',
    sortByAdded: 'ترتيب الإضافة',
    noVideoFiles: 'لم يتم العثور على ملفات فيديو. الصيغ المدعومة: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'تمت إضافة ملف(ملفات) فيديو',
    tooltipAdd: 'إضافة ملفات فيديو أو مجلدات إلى القائمة',
    tooltipGenerate: 'إنشاء بيانات وصفية (عنوان، وصف، هاشتاغات) للفيديوهات المحددة باستخدام الذكاء الاصطناعي',
    tooltipAutoSchedule: 'تعيين أوقات النشر تلقائيًا بناءً على إعدادات الجدولة',
    tooltipAutoUpload: 'تفعيل جدولة التحميل التلقائي. YouTube: تلقائي بالكامل. Instagram/TikTok: مساعدة يدوية',
    tooltipSilentMode: 'الوضع الصامت: إرسال إشعار فقط، عدم فتح المتصفح تلقائيًا (يمنع الانقطاعات)',
    tooltipRecalculate: 'إعادة حساب أوقات النشر لجميع الفيديوهات بناءً على ترتيب الفرز الحالي وإعدادات الجدولة',
    tooltipConnectYouTube: 'ربط حساب YouTube الخاص بك لتفعيل التحميلات التلقائية',
    tooltipUploadYouTube: 'تحميل الفيديو المحدد على YouTube فورًا',
    tooltipCopy: 'نسخ إلى الحافظة',
    tooltipReload: 'إعادة تحميل البيانات الوصفية من مخرجات خط الأنابيب',
    tooltipOpenExports: 'فتح مجلد الصادرات لهذه المنصة',
    tooltipOpenOutputs: 'فتح مجلد المخرجات الرئيسي',
    tooltipRemove: 'إزالة هذا الفيديو من القائمة',
    tooltipSort: 'ترتيب الفيديوهات حسب الاسم أو تاريخ الإنشاء أو ترتيب الإضافة',
    autoSchedule: 'جدولة تلقائية',
    autoUpload: 'تحميل تلقائي',
    silent: 'صامت',
    connected: 'متصل',
    connectYouTube: 'ربط YouTube',
    check: 'تحقق',
    openUserData: 'فتح UserData',
    timeZone: 'المنطقة الزمنية',
    notConnected: 'غير متصل',
    youtubeConnected: 'YouTube: متصل',
    youtubeNotConnected: 'YouTube: غير متصل',
    publishAt: 'نشر في',
    deleteMetadataConfirm: 'هل أنت متأكد أنك تريد حذف البيانات الوصفية لـ {platform}؟',
    deleteMetadataConfirmTitle: 'حذف البيانات الوصفية؟',
    publishStarted: 'تم بدء النشر',
    publishButtonGenerate: 'إنشاء',
    publishButtonYouTube: 'نشر على YouTube',
    publishButtonAll: 'نشر في كل مكان',
    posted: 'تم النشر',
    postedAt: 'تم النشر في',
  },
  hi: {
    add: 'जोड़ें (फ़ाइलें या फ़ोल्डर)',
    generate: 'मेटाडेटा जेनरेट करें',
    selectAll: 'सभी चुनें',
    deselectAll: 'सभी अचयनित करें',
    details: 'विवरण',
    selectRow: 'एक पंक्ति चुनें।',
    file: 'फ़ाइल',
    status: 'स्थिति',
    visibility: 'दृश्यता',
    schedule: 'अनुसूची',
    publish: 'प्रकाशित करें',
    recalculate: 'पुनर्गणना',
    editsTz: 'संपादन चयनित समय क्षेत्र में लागू होते हैं',
    resetAuto: 'स्वचालित अनुसूची पर रीसेट करें',
    metadata: 'मेटाडेटा',
    platform: 'प्लेटफ़ॉर्म',
    title: 'शीर्षक',
    description: 'विवरण',
    hashtags: 'हैशटैग',
    copy: 'कॉपी करें',
    copyAll: 'सभी कॉपी करें',
    copied: 'कॉपी किया गया',
    openExports: 'निर्यात खोलें',
    openOutputs: 'आउटपुट खोलें',
    reload: 'रीलोड करें',
    source: 'स्रोत',
    pipelineLog: 'पाइपलाइन लॉग',
    noRow: 'कोई पंक्ति चयनित नहीं।',
    settings: 'सेटिंग्स',
    uiSize: 'UI आकार',
    theme: 'थीम',
    day: 'दिन',
    night: 'रात',
    language: 'भाषा',
    account: 'खाता',
    manageBilling: 'बिलिंग प्रबंधित करें',
    subscription: 'सदस्यता',
    comingSoon: 'जल्दी आ रहा है',
    collapseAll: 'संकुचित करें',
    expandAll: 'विस्तार करें',
    dragDropFiles: 'वीडियो फ़ाइलें यहाँ खींचें',
    dragDropFormats: 'समर्थित प्रारूप: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: 'हटाएं',
    sortBy: 'क्रमबद्ध करें',
    sortByName: 'नाम (A-Z)',
    sortByDate: 'निर्माण तिथि',
    sortByAdded: 'जोड़ने का क्रम',
    noVideoFiles: 'कोई वीडियो फ़ाइल नहीं मिली। समर्थित प्रारूप: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: 'वीडियो फ़ाइल(ें) जोड़ी गई',
    tooltipAdd: 'सूची में वीडियो फ़ाइलें या फ़ोल्डर जोड़ें',
    tooltipGenerate: 'AI का उपयोग करके चयनित वीडियो के लिए मेटाडेटा (शीर्षक, विवरण, हैशटैग) जेनरेट करें',
    tooltipAutoSchedule: 'अनुसूची सेटिंग्स के आधार पर स्वचालित रूप से प्रकाशन समय निर्दिष्ट करें',
    tooltipAutoUpload: 'स्वचालित अपलोड शेड्यूलर सक्षम करें। YouTube: पूर्ण स्वचालित। Instagram/TikTok: मैनुअल सहायता',
    tooltipSilentMode: 'साइलेंट मोड: केवल सूचना भेजें, ब्राउज़र को स्वचालित रूप से न खोलें (बाधाओं को रोकता है)',
    tooltipRecalculate: 'वर्तमान सॉर्ट क्रम और अनुसूची सेटिंग्स के आधार पर सभी वीडियो के लिए प्रकाशन समय पुनर्गणना करें',
    tooltipConnectYouTube: 'स्वचालित अपलोड सक्षम करने के लिए अपना YouTube खाता कनेक्ट करें',
    tooltipUploadYouTube: 'चयनित वीडियो को तुरंत YouTube पर अपलोड करें',
    tooltipCopy: 'क्लिपबोर्ड पर कॉपी करें',
    tooltipReload: 'पाइपलाइन आउटपुट से मेटाडेटा रीलोड करें',
    tooltipOpenExports: 'इस प्लेटफ़ॉर्म के लिए निर्यात फ़ोल्डर खोलें',
    tooltipOpenOutputs: 'मुख्य आउटपुट फ़ोल्डर खोलें',
    tooltipRemove: 'इस वीडियो को सूची से हटाएं',
    tooltipSort: 'नाम, निर्माण तिथि या जोड़ने के क्रम के अनुसार वीडियो क्रमबद्ध करें',
    autoSchedule: 'स्वचालित अनुसूची',
    autoUpload: 'स्वचालित अपलोड',
    silent: 'मौन',
    connected: 'जुड़ा हुआ',
    connectYouTube: 'YouTube कनेक्ट करें',
    check: 'जांचें',
    openUserData: 'UserData खोलें',
    timeZone: 'समय क्षेत्र',
    notConnected: 'जुड़ा नहीं',
    youtubeConnected: 'YouTube: जुड़ा हुआ',
    youtubeNotConnected: 'YouTube: जुड़ा नहीं',
    publishAt: 'प्रकाशित करें',
    deleteMetadataConfirm: 'क्या आप वाकई {platform} के लिए मेटाडेटा हटाना चाहते हैं?',
    deleteMetadataConfirmTitle: 'मेटाडेटा हटाएं?',
    publishStarted: 'प्रकाशन शुरू',
    publishButtonGenerate: 'जेनरेट करें',
    publishButtonYouTube: 'YouTube पर प्रकाशित करें',
    publishButtonAll: 'हर जगह प्रकाशित करें',
    posted: 'प्रकाशित',
    postedAt: 'प्रकाशित किया गया',
  },
  zh: {
    add: '添加（文件或文件夹）',
    generate: '生成元数据',
    selectAll: '全选',
    deselectAll: '取消全选',
    details: '详细信息',
    selectRow: '选择一行。',
    file: '文件',
    status: '状态',
    visibility: '可见性',
    schedule: '安排',
    publish: '发布',
    recalculate: '重新计算',
    editsTz: '编辑将应用于所选时区',
    resetAuto: '重置为自动安排',
    metadata: '元数据',
    platform: '平台',
    title: '标题',
    description: '描述',
    hashtags: '标签',
    copy: '复制',
    copyAll: '全部复制',
    copied: '已复制',
    openExports: '打开导出',
    openOutputs: '打开输出',
    reload: '重新加载',
    source: '来源',
    pipelineLog: '管道日志',
    noRow: '未选择行。',
    settings: '设置',
    uiSize: '界面大小',
    theme: '主题',
    day: '白天',
    night: '夜间',
    language: '语言',
    account: '账户',
    manageBilling: '管理计费',
    subscription: '订阅',
    comingSoon: '即将推出',
    collapseAll: '折叠',
    expandAll: '展开',
    dragDropFiles: '将视频文件拖放到此处',
    dragDropFormats: '支持的格式：MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: '删除',
    sortBy: '排序方式',
    sortByName: '名称 (A-Z)',
    sortByDate: '创建日期',
    sortByAdded: '添加顺序',
    noVideoFiles: '未找到视频文件。支持的格式：mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: '已添加视频文件',
    tooltipAdd: '将视频文件或文件夹添加到列表',
    tooltipGenerate: '使用AI为选定的视频生成元数据（标题、描述、标签）',
    tooltipAutoSchedule: '根据计划设置自动分配发布时间',
    tooltipAutoUpload: '启用自动上传调度器。YouTube：完全自动。Instagram/TikTok：手动协助',
    tooltipSilentMode: '静音模式：仅发送通知，不自动打开浏览器（防止中断）',
    tooltipRecalculate: '根据当前排序顺序和计划设置重新计算所有视频的发布时间',
    tooltipConnectYouTube: '连接您的YouTube账户以启用自动上传',
    tooltipUploadYouTube: '立即将选定的视频上传到YouTube',
    tooltipCopy: '复制到剪贴板',
    tooltipReload: '从管道输出重新加载元数据',
    tooltipOpenExports: '打开此平台的导出文件夹',
    tooltipOpenOutputs: '打开主输出文件夹',
    tooltipRemove: '从列表中删除此视频',
    tooltipSort: '按名称、创建日期或添加顺序对视频进行排序',
    autoSchedule: '自动安排',
    autoUpload: '自动上传',
    silent: '静音',
    connected: '已连接',
    connectYouTube: '连接 YouTube',
    check: '检查',
    openUserData: '打开 UserData',
    timeZone: '时区',
    notConnected: '未连接',
    youtubeConnected: 'YouTube: 已连接',
    youtubeNotConnected: 'YouTube: 未连接',
    publishAt: '发布时间',
    deleteMetadataConfirm: '您确定要删除 {platform} 的元数据吗？',
    deleteMetadataConfirmTitle: '删除元数据？',
    publishStarted: '发布已开始',
    publishButtonGenerate: '生成',
    publishButtonYouTube: '发布到 YouTube',
    publishButtonAll: '发布到所有平台',
    posted: '已发布',
    postedAt: '发布于',
  },
  ja: {
    add: '追加（ファイルまたはフォルダ）',
    generate: 'メタデータを生成',
    selectAll: 'すべて選択',
    deselectAll: 'すべて選択解除',
    details: '詳細',
    selectRow: '行を選択してください。',
    file: 'ファイル',
    status: 'ステータス',
    visibility: '公開設定',
    schedule: 'スケジュール',
    publish: '公開',
    recalculate: '再計算',
    editsTz: '編集は選択したタイムゾーンで適用されます',
    resetAuto: '自動スケジュールにリセット',
    metadata: 'メタデータ',
    platform: 'プラットフォーム',
    title: 'タイトル',
    description: '説明',
    hashtags: 'ハッシュタグ',
    copy: 'コピー',
    copyAll: 'すべてコピー',
    copied: 'コピーしました',
    openExports: 'エクスポートを開く',
    openOutputs: '出力を開く',
    reload: '再読み込み',
    source: 'ソース',
    pipelineLog: 'パイプラインログ',
    noRow: '行が選択されていません。',
    settings: '設定',
    uiSize: 'UIサイズ',
    theme: 'テーマ',
    day: '昼',
    night: '夜',
    language: '言語',
    account: 'アカウント',
    manageBilling: '請求を管理',
    subscription: 'サブスクリプション',
    comingSoon: '近日公開',
    collapseAll: '折りたたむ',
    expandAll: '展開',
    dragDropFiles: '動画ファイルをここにドラッグ',
    dragDropFormats: 'サポート形式：MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: '削除',
    sortBy: '並び替え',
    sortByName: '名前 (A-Z)',
    sortByDate: '作成日',
    sortByAdded: '追加順',
    noVideoFiles: '動画ファイルが見つかりません。サポート形式：mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: '動画ファイルが追加されました',
    tooltipAdd: 'リストに動画ファイルまたはフォルダを追加',
    tooltipGenerate: 'AIを使用して選択した動画のメタデータ（タイトル、説明、ハッシュタグ）を生成',
    tooltipAutoSchedule: 'スケジュール設定に基づいて公開時間を自動的に割り当て',
    tooltipAutoUpload: '自動アップロードスケジューラーを有効化。YouTube：完全自動。Instagram/TikTok：手動アシスト',
    tooltipSilentMode: 'サイレントモード：通知のみ送信、ブラウザを自動的に開かない（中断を防ぐ）',
    tooltipRecalculate: '現在の並び替え順序とスケジュール設定に基づいてすべての動画の公開時間を再計算',
    tooltipConnectYouTube: '自動アップロードを有効にするためにYouTubeアカウントを接続',
    tooltipUploadYouTube: '選択した動画をすぐにYouTubeにアップロード',
    tooltipCopy: 'クリップボードにコピー',
    tooltipReload: 'パイプライン出力からメタデータを再読み込み',
    tooltipOpenExports: 'このプラットフォームのエクスポートフォルダを開く',
    tooltipOpenOutputs: 'メイン出力フォルダを開く',
    tooltipRemove: 'この動画をリストから削除',
    tooltipSort: '名前、作成日、または追加順で動画を並び替え',
    autoSchedule: '自動スケジュール',
    autoUpload: '自動アップロード',
    silent: 'サイレント',
    connected: '接続済み',
    connectYouTube: 'YouTubeを接続',
    check: '確認',
    openUserData: 'UserDataを開く',
    timeZone: 'タイムゾーン',
    notConnected: '未接続',
    youtubeConnected: 'YouTube: 接続済み',
    youtubeNotConnected: 'YouTube: 未接続',
    publishAt: '公開時刻',
    deleteMetadataConfirm: '{platform} のメタデータを削除してもよろしいですか？',
    deleteMetadataConfirmTitle: 'メタデータを削除しますか？',
    publishStarted: '公開を開始しました',
    publishButtonGenerate: '生成',
    publishButtonYouTube: 'YouTubeに公開',
    publishButtonAll: 'すべてに公開',
    posted: '公開済み',
    postedAt: '公開日時',
  },
  ko: {
    add: '추가 (파일 또는 폴더)',
    generate: '메타데이터 생성',
    selectAll: '모두 선택',
    deselectAll: '모두 선택 해제',
    details: '세부 정보',
    selectRow: '행을 선택하세요.',
    file: '파일',
    status: '상태',
    visibility: '공개 설정',
    schedule: '일정',
    publish: '게시',
    recalculate: '재계산',
    editsTz: '편집은 선택한 시간대에 적용됩니다',
    resetAuto: '자동 일정으로 재설정',
    metadata: '메타데이터',
    platform: '플랫폼',
    title: '제목',
    description: '설명',
    hashtags: '해시태그',
    copy: '복사',
    copyAll: '모두 복사',
    copied: '복사됨',
    openExports: '내보내기 열기',
    openOutputs: '출력 열기',
    reload: '다시 로드',
    source: '소스',
    pipelineLog: '파이프라인 로그',
    noRow: '행이 선택되지 않았습니다.',
    settings: '설정',
    uiSize: 'UI 크기',
    theme: '테마',
    day: '낮',
    night: '밤',
    language: '언어',
    account: '계정',
    manageBilling: '청구 관리',
    subscription: '구독',
    comingSoon: '곧 출시',
    collapseAll: '접기',
    expandAll: '펼치기',
    dragDropFiles: '비디오 파일을 여기로 드래그',
    dragDropFormats: '지원 형식: MP4, MOV, AVI, MKV, WEBM, FLV, WMV, M4V',
    removeVideo: '제거',
    sortBy: '정렬 기준',
    sortByName: '이름 (A-Z)',
    sortByDate: '생성 날짜',
    sortByAdded: '추가 순서',
    noVideoFiles: '비디오 파일을 찾을 수 없습니다. 지원 형식: mp4, mov, avi, mkv, webm, flv, wmv, m4v',
    filesAdded: '비디오 파일 추가됨',
    tooltipAdd: '목록에 비디오 파일 또는 폴더 추가',
    tooltipGenerate: 'AI를 사용하여 선택한 비디오의 메타데이터 (제목, 설명, 해시태그) 생성',
    tooltipAutoSchedule: '일정 설정에 따라 게시 시간을 자동으로 할당',
    tooltipAutoUpload: '자동 업로드 스케줄러 활성화. YouTube: 완전 자동. Instagram/TikTok: 수동 지원',
    tooltipSilentMode: '조용한 모드: 알림만 전송, 브라우저를 자동으로 열지 않음 (중단 방지)',
    tooltipRecalculate: '현재 정렬 순서와 일정 설정에 따라 모든 비디오의 게시 시간 재계산',
    tooltipConnectYouTube: '자동 업로드를 활성화하려면 YouTube 계정 연결',
    tooltipUploadYouTube: '선택한 비디오를 즉시 YouTube에 업로드',
    tooltipCopy: '클립보드에 복사',
    tooltipReload: '파이프라인 출력에서 메타데이터 다시 로드',
    tooltipOpenExports: '이 플랫폼의 내보내기 폴더 열기',
    tooltipOpenOutputs: '메인 출력 폴더 열기',
    tooltipRemove: '이 비디오를 목록에서 제거',
    tooltipSort: '이름, 생성 날짜 또는 추가 순서로 비디오 정렬',
    autoSchedule: '자동 일정',
    autoUpload: '자동 업로드',
    silent: '조용한',
    connected: '연결됨',
    connectYouTube: 'YouTube 연결',
    check: '확인',
    openUserData: 'UserData 열기',
    timeZone: '시간대',
    notConnected: '연결 안 됨',
    youtubeConnected: 'YouTube: 연결됨',
    youtubeNotConnected: 'YouTube: 연결 안 됨',
    publishAt: '게시 시간',
    deleteMetadataConfirm: '{platform}의 메타데이터를 삭제하시겠습니까?',
    deleteMetadataConfirmTitle: '메타데이터 삭제?',
    publishStarted: '게시 시작됨',
    publishButtonGenerate: '생성',
    publishButtonYouTube: 'YouTube에 게시',
    publishButtonAll: '모든 곳에 게시',
    posted: '게시됨',
    postedAt: '게시 시간',
  },
};
